safe: true
name: "SiteWhere Documentation"
url: "http://localhost:4000"
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]